baseurl = "http://rakuishi.com/"
languageCode = "ja"
title = "DhamarHusa.In"
author = "Dhamar Husain"
copyright = "dhamarhusa.in All rights reserved."
googleanalytics = ""
theme = "hugo-zen"
paginate = 7
canonifyURLs = true
[params]
  subtitle = "Ini Cuman Blog Pribadi."
  logo      = "/img/avatar.jpg"