baseurl = "/"
languageCode = "id"
title = "Dhamar's blog"
theme = 'tema'
summarylength = 20
hasCJKLanguage = true

[author]
 author = 'dhamar'
 profile = 'Seorang full stack web developer tinggal di jawa tengah, indonesia.'
 image = 'image/theme/profile.jpg'

[Params]
 localeOgp = "id"
 description = "ini cuman blog pribadi tidak lebih"
 keywords = "indonesia,linux,programmer,Web,pribadi,dhamarhusainsm"
 twitter = ""
 github = "dhamarhusainsm"
 facebook = "dhamarhusainsm"
 googleanalytics = " UA-121887690-1 "
 googlecustomsearch = "003263178205246839651:jrhhbtpuctm"